namespace Assets.HeroEditor.FantasyInventory.Scripts.Enums
{
    public enum ItemClass
    {
        Unknown,
        Dagger,
        Sword,
        Axe,
        Blunt,
        Lance,
        Wand,
        Bow,
        Light,
        Heavy,
        Ring,
        Necklace,
        Food,
        Potion,
        Scroll,
        Bomb,
        Booster,
        Pickaxe,
        Claw,
        Fang,
        Skin,
        Firearm,
        Talisman
    }
}